spring:
  config:
    activate:
      on-profile: docker

  application:
    name: biked

  datasource:
    url: jdbc:postgresql://db:5432/biked
    username: biked
    password: biked123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: minha-chave-secreta-muito-longa-para-jwt-256-bits-minimo-ok
  expiration: 86400000 # 24h